#!/usr/bin/env python

import loos
import loos.pyloos
import sys
import numpy
import copy
import os
import h5py
### The purpose of this script is to read the hdf file from the output of w_pdist then create just rows of lines so that we can use gnuplot to create figures
### pdisth5: is the input we take in as the first of the commandline
pdisth5 =h5py.File(sys.argv[1],'r')
### Readthis heading in the hdf file and find the corresponding data
histogram_name = '/histogram'
histogram_data  = pdisth5[histogram_name]
histogram = numpy.array(histogram_data)

first = int(sys.argv[2])
last =  int(sys.argv[3])
subset_array = histogram[first:last:1]
### if it is 2D there will be two mid points in the histogram generated by w_pdist
pcoord =  pdisth5['/midpoints_0']
auxiliary = pdisth5['/midpoints_1']
### print the progress coordinate, auxiliary data and the probability value
for i in range(pcoord.shape[0]):
    for j in range(auxiliary.shape[0]):
        print pcoord[i],"\t",auxiliary[j],"\t",histogram[i][j]
